version: '3.8'

services:
  back:
    container_name: back
    build:
      context: ./back
    restart: always

  front:
    container_name: front
    build:
      context: ./front
    depends_on:
      - back
    restart: always

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - back
      - front
    restart: always
